### ISSUE TITLE
Typo on homepage, 'submited' vs 'submitted'

### ISSUE THREAD

**Issue by cabiad** [openfoodfacts/openfoodfacts-web#351]
### What
The word 'submitted' is misspelled as 'submited' in the FAQ. This seemingly affects HTML contents across multiple language copies of this file.

### Steps to reproduce the behavior:
1. Go to (for example) 'https://world.openfoodfacts.org/faq#data_verification'
2. See the word 'submited' is misspelled.

### Expected behavior
Word should be spelled 'submitted'

### Screenshots
<img width="1293" alt="image" src="https://user-images.githubusercontent.com/840172/208985841-c50dc8b7-f433-4bac-8d0e-26b4931bc788.png">

### Platform (Desktop, Mobile, Hunger Games)
 - OS: All
 - Platform: Web

**Comment by teolemon** [comment]
Thanks @hangy for the review
Congratulations @cabiad for your first pr to Open Food Facts 🍾
