### ISSUE TITLE
Many images are 404 on the pro website

### ISSUE THREAD

**Issue by Flaburgan** [openfoodfacts/openfoodfacts-web#501]
Hello,

I don't know if this is the good github repository, but there are many images which are 404 on the official website.

For example, 26 of them on https://world.pro.openfoodfacts.org/ : 
![image](https://github.com/openfoodfacts/openfoodfacts-web/assets/930064/01dd37a8-e0c8-4dd8-91ee-8567a9d0171b)

Thanks for the good work you're doing!

**Comment by stephanegigandet** [comment]
Those images are not in github (not in openfoodfacts-web and not in openfoodfacts-server).
They should be added to openfoodfacts-server

https://world.openfoodfacts.org/images/producers/validated-data.png
