### ISSUE TITLE
Missing page https://ch.openfoodfacts.org/wer-wir-sind

### ISSUE THREAD

**Issue by SaimenAndSchwyter** [openfoodfacts/openfoodfacts-web#587]
### What
When i navigate to https://ch.openfoodfacts.org/wer-wir-sind in the footer (HTML id contribute_and_discover_links_block) an error is shown that the page does not exist.

### Steps to reproduce the behavior
1. I navigate to https://ch.openfoodfacts.org/wer-wir-sind
2. An error is shown in german "Fehler - Ungültige Adresse"

### Expected behavior
The page should show the content of the who we are page in german.

### Screenshot/Mockup/Before-After
![image](https://github.com/openfoodfacts/openfoodfacts-androidapp/assets/22655223/afdd6b7c-4a08-4d77-8356-fc5ed4e2d2c4)

### Important information
 - Device: Laptop
 - Plattform: Desktop Website (Edge Chromium)

**Comment by alexgarel** [comment]
Thanks @SaimenAndSchwyter !
