### ISSUE TITLE
Crowdin action fails

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-web#6]
❌ Failed to upload the translation file to the storage. Please contact our support team for help
❌ Error from server: <Code: <empty_code>, Message: Operation timed out (Read failed)>
❌ Current execution finished with errors

**Comment by yarons** [comment]
Is that an error message from Crowdin? Do you have a support ticket open with them?

**Comment by teolemon** [comment]
I've just fixed it, closing.
